### ISSUE TITLE
Remap Classical - UnboundLocalError: local variable 'comments' referenced before assignment

### ISSUE THREAD

**Issue by rokdd** [Josef-Friedrich/audiorename#2]
I get the following error with using remap classical flag:
```
File "/home/xxx/xx/lib/python3.8/site-packages/audiorename/meta.py", line 446, in remap_classical
    self.comments = comments
UnboundLocalError: local variable 'comments' referenced before assignment
```
I watched your code, and I am not sure whether the indent is wrong (and it belongs to the if clause) or comments should be always appended..

**Comment by Josef-Friedrich** [comment]
Thank you for reporting this issue. You are right, the indentation was wrong.

**Comment by rokdd** [comment]
Well I fixed in my fork and thought I fixed it wrong:

```
Delgarma - Que vive l'industrie/1-08 Bora dumhet_1.mp3
Remap classical
    comments:                “Original metadata: title: Bora dumhet; artist: Delgarma; ”
                             “Original metadata: title: Bora dumhet; artist: ?ÿþd / a / m / i / e / n /   / v / e / r / r / e / c / c / h / i / a /   / - /   / l / a / i / l / a /   / r / o / u / x / T; ”
    Move
        […]/var/xxxxx/Delgarma - Que vive l'industrie/1-08 Bora dumhet_1.mp3
        to:
        […]/ÿþd/_[Delgarma]/08_Bora dumhet_.mp3
Traceback (most recent call last):
  File "/home/xx/env-audiorename/bin/audiorenamer", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/xx/env-audiorename/src/audiorename/bin/audiorenamer", line 5, in <module>
    execute()
  File "/home/xx/env-audiorename/src/audiorename/audiorename/__init__.py", line 32, in execute
...
PermissionError: [Errno 13] Permission denied: '/\x01ÿþd'
```

**Comment by Josef-Friedrich** [comment]
I m not sure. Is the issue fixed or not? I have to admit that I haven't used this option for a long time
