### ISSUE TITLE
Cannnot install audiorename

### ISSUE THREAD

**Issue by reagle** [Josef-Friedrich/audiorename#27]
Using python 3.12, installed by pyenv.

```
❯ pip install audiorename
Collecting audiorename
  Using cached audiorename-3.3.0.tar.gz (78 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [31 lines of output]
      /private/var/folders/2l/73vdx0sd5rvcn38yg036h6500000gp/T/pip-install-i8i3no6k/audiorename_5c8d9ab30baf4828a3525251cfbc5540/versioneer.py:421: SyntaxWarning: invalid escape sequence '\s'
        LONG_VERSION_PY['git'] = '''
      Traceback (most recent call last):
        File "/Users/reagle/.pyenv/versions/3.12.7/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/reagle/.pyenv/versions/3.12.7/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/reagle/.pyenv/versions/3.12.7/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/2l/73vdx0sd5rvcn38yg036h6500000gp/T/pip-build-env-nz169_b3/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 334, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/2l/73vdx0sd5rvcn38yg036h6500000gp/T/pip-build-env-nz169_b3/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 304, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/2l/73vdx0sd5rvcn38yg036h6500000gp/T/pip-build-env-nz169_b3/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 522, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/private/var/folders/2l/73vdx0sd5rvcn38yg036h6500000gp/T/pip-build-env-nz169_b3/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 320, in run_setup
          exec(code, locals())
        File "<string>", line 23, in <module>
        File "/private/var/folders/2l/73vdx0sd5rvcn38yg036h6500000gp/T/pip-install-i8i3no6k/audiorename_5c8d9ab30baf4828a3525251cfbc5540/versioneer.py", line 1480, in get_version
          return get_versions()["version"]
                 ^^^^^^^^^^^^^^
        File "/private/var/folders/2l/73vdx0sd5rvcn38yg036h6500000gp/T/pip-install-i8i3no6k/audiorename_5c8d9ab30baf4828a3525251cfbc5540/versioneer.py", line 1412, in get_versions
          cfg = get_config_from_root(root)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/2l/73vdx0sd5rvcn38yg036h6500000gp/T/pip-install-i8i3no6k/audiorename_5c8d9ab30baf4828a3525251cfbc5540/versioneer.py", line 342, in get_config_from_root
          parser = configparser.SafeConfigParser()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip
```

**Comment by Josef-Friedrich** [comment]
The version on PyPI is not ready for Python3.12. I must release a new version ... 

The main branch in this repo should be ready for 3.12, for example:

```
pipx install git+https://github.com/Josef-Friedrich/audiorename.git
```

**Comment by Josef-Friedrich** [comment]
https://pypi.org/project/audiorename/4.0.0/

**Comment by reagle** [comment]
Thank you, I can confirm it installs.

**Comment by reagle** [comment]
I'm having this problem again and trying to install version 4.0.0 doesn't work.

```
❯ pip install audiorename==4.0.0
ERROR: Could not find a version that satisfies the requirement audiorename==4.0.0 (from versions: 1.2.4, 1.2.5, 1.2.6, 1.3.0, 2.0.1, 2.1.0, 2.1.1, 3.0.0a1, 3.0.0a2, 3.0.0a3, 3.0.0, 3.1.0, 3.2.0, 3.2.1, 3.3.0)
ERROR: No matching distribution found for audiorename==4.0.0
```

**Comment by Josef-Friedrich** [comment]
I can not reproduce this problem

![Image](https://github.com/user-attachments/assets/b9863c50-45ad-46fc-8566-bb3b9584b477)

![Image](https://github.com/user-attachments/assets/d536aa7d-6dfa-40ec-b153-a03f3b6fa839)

A caching issue? Python must be >=3.9?

Have you tried:

```
pipx install git+https://github.com/Josef-Friedrich/audiorename.git
```
