### ISSUE TITLE
Broken m4a files

### ISSUE THREAD

**Issue by rokdd** [Josef-Friedrich/audiorename#9]
I have some m4a files which always are reported as broken (and do not get moved). I tried out to find the reason for the broken file and I got not so much clue where it gets detected in your code. I only found out, that all files with a fixed Bitrate are working and with a VBR bitrate are not working. When you need an example file I can provide you by PM. Is there a limitation of the library?

**Comment by Josef-Friedrich** [comment]
I forced audiorename to throw exceptions on your file

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/mutagen/mp4/__init__.py", line 1083, in load
    self.tags = self.MP4Tags(atoms, fileobj)
  File "/usr/lib/python3/dist-packages/mutagen/mp4/__init__.py", line 344, in __init__
    self.load(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/mutagen/mp4/__init__.py", line 364, in load
    info[0](self, atom, data)
  File "/usr/lib/python3/dist-packages/mutagen/mp4/__init__.py", line 599, in __parse_freeform
    length = cdata.uint_be(data[pos:pos + 4])
  File "/usr/lib/python3/dist-packages/mutagen/_util.py", line 558, in <lambda>
    get_wrapper = lambda f: lambda *a, **k: f(*a, **k)[0]
struct.error: unpack requires a buffer of 4 bytes

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/phrydy-2.0.0-py3.8.egg/phrydy/mediafile.py", line 131, in mutagen_call
    return func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/mutagen/_util.py", line 148, in wrapper_func
    return func(h, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/mutagen/_file.py", line 300, in File
    return Kind(fileobj, filename=filething.filename)
  File "/usr/lib/python3/dist-packages/mutagen/_file.py", line 49, in __init__
    self.load(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/mutagen/_util.py", line 140, in wrapper
    return func(self, h, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/mutagen/mp4/__init__.py", line 1087, in load
    reraise(MP4MetadataError, err, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/mutagen/_compat.py", line 88, in reraise
    raise tp(value).with_traceback(tb)
  File "/usr/lib/python3/dist-packages/mutagen/mp4/__init__.py", line 1083, in load
    self.tags = self.MP4Tags(atoms, fileobj)
  File "/usr/lib/python3/dist-packages/mutagen/mp4/__init__.py", line 344, in __init__
    self.load(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/mutagen/mp4/__init__.py", line 364, in load
    info[0](self, atom, data)
  File "/usr/lib/python3/dist-packages/mutagen/mp4/__init__.py", line 599, in __parse_freeform
    length = cdata.uint_be(data[pos:pos + 4])
  File "/usr/lib/python3/dist-packages/mutagen/_util.py", line 558, in <lambda>
    get_wrapper = lambda f: lambda *a, **k: f(*a, **k)[0]
mutagen.mp4.MP4MetadataError: unpack requires a buffer of 4 bytes

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/audiorenamer", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/jf/repos/github/audiorename/bin/audiorenamer", line 5, in <module>
    execute()
  File "/home/jf/repos/github/audiorename/audiorename/__init__.py", line 32, in execute
    batch.execute()
  File "/home/jf/repos/github/audiorename/audiorename/batch.py", line 129, in execute
    do_job_on_audiofile(p, job=self.job)
  File "/home/jf/repos/github/audiorename/audiorename/audiofile.py", line 291, in do_job_on_audiofile
    source = AudioFile(source, prefix=os.getcwd(), file_type='source', job=job)
  File "/home/jf/repos/github/audiorename/audiorename/audiofile.py", line 38, in __init__
    self.meta = Meta(self.abspath, shell_friendly)
  File "/home/jf/repos/github/audiorename/audiorename/meta.py", line 333, in __init__
    super(Meta, self).__init__(path, False)
  File "/usr/local/lib/python3.8/dist-packages/phrydy-2.0.0-py3.8.egg/phrydy/mediafile.py", line 1449, in __init__
    self.mgfile = mutagen_call('open', path, mutagen.File, path)
  File "/usr/local/lib/python3.8/dist-packages/phrydy-2.0.0-py3.8.egg/phrydy/mediafile.py", line 134, in mutagen_call
    raise UnreadableFileError(path, six.text_type(exc))
phrydy.mediafile.UnreadableFileError: unpack requires a buffer of 4 bytes
```

maybe related: 

https://community.metabrainz.org/t/error-unpack-requires-a-buffer-of-4-bytes-when-scanning-m4a-files-suddenly/440226

I tried the mutagen version 1.39 and 1.44

**Comment by rokdd** [comment]
I followed the steps and discussions at [https://tickets.metabrainz.org/browse/PICARD-1605](https://tickets.metabrainz.org/browse/PICARD-1605), because indeed I am using MusicBee as well:

> To batch remove the bad tag ("----") and fix the music library. There is a "remove tag" option within musicbee. Tools -> Tagging Tools -> Remove Tags...
> 
> With the file selected, you select "----" and it works.
I always selected a bunch of files (every 20000 around) else it stuck. And it makes sense to remove all missing files before: Tools -> Tagging Tools -> Other 'Files to Edit' -> Show Dead Links.
